# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
job_configuration: &job_configuration
  docker:
    - image: circleci/node
  working_directory: ~/repo
install_bazel: &install_bazel
  run:
    name: Install Bazel
    command: |
      sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
      BAZEL_VERSION=0.22.0
      BAZEL_INSTALL_SCRIPT=bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
      wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/$BAZEL_INSTALL_SCRIPT
      chmod +x $BAZEL_INSTALL_SCRIPT
      sudo ./$BAZEL_INSTALL_SCRIPT
jobs:
  build:
    <<: *job_configuration
    steps:
      - checkout
      - *install_bazel
      - run:
          name: Build
          command: bazel build //...
  build_dockerized_example:
    <<: *job_configuration
    steps:
      - checkout
      - setup_remote_docker
      - *install_bazel
      - run:
          name: Build Dockerized TypeScript Node example
          command: |
            cd examples/node-typescript-app
            bazel build //...
            bazel run //services/my-service:image
            docker run -d -p 3000:3000 bazel/services/my-service:image
  build_react_examples:
    <<: *job_configuration
    steps:
      - checkout
      - *install_bazel
      - run:
          name: Build React examples
          command: |
            cd examples/react-app-javascript
            bazel build //...
            cd -
            cd examples/react-app-typescript
            bazel build //...
            cd -
            cd examples/react-storybook-typescript
            bazel build //...
            cd -
  build_react_app_with_node_modules_preinstalled:
    <<: *job_configuration
    steps:
      - checkout
      - *install_bazel
      - run:
          name: Build React example with node_modules already installed
          command: |
            # Install node_modules to give Node the opportunity to get confused.
            cd examples/react-app-javascript
            yarn install
            bazel build ...
  buildifier-check:
    docker:
      - image: circleci/golang
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Buildifier
          command: |
            go get github.com/bazelbuild/buildtools/buildifier
      - run:
          name: Buildifier check
          command: |
            buildifier -mode=check $(find . -type f \( -iname BUILD -or -iname BUILD.bazel -or -iname "*.bzl" \))
  prettier-check:
    <<: *job_configuration
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Prettier
          command: |
            ./node_modules/.bin/prettier --list-different "**/*.js" "**/*.jsx" "**/*.ts" "**/*.tsx"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_react_examples
      - build_react_app_with_node_modules_preinstalled
      - build_dockerized_example
      - buildifier-check
      - prettier-check
